# Generated by Django 5.2.4 on 2025-08-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phones',
            new_name='Phone',
        ),
    ]
