# Generated by Django 5.2.4 on 2025-08-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_phones_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
