# Generated by Django 5.2.4 on 2025-08-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_phone_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='battery',
            field=models.TextField(),
        ),
    ]
