# Generated by Django 5.2.4 on 2025-08-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_phone_battery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='ram',
            field=models.CharField(choices=[('2 GB', '2 GB'), ('3 GB', '3 GB'), ('4 GB', '4 GB'), ('6 GB', '6 GB'), ('8 GB', '8 GB'), ('12 GB', '12 GB'), ('16 GB', '16 GB'), ('18 GB', '18 GB'), ('24 GB', '24 GB')], max_length=10),
        ),
        migrations.AlterField(
            model_name='phone',
            name='storage',
            field=models.CharField(choices=[('8 GB', '8 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('1 TB', '1 TB'), ('2 TB', '2 TB')], max_length=10),
        ),
    ]
