# Generated by Django 5.2.4 on 2025-08-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_phone_ram_alter_phone_storage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='color_type',
            new_name='color',
        ),
    ]
