# Generated by Django 5.2.4 on 2025-08-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_color_type_phone_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='ram',
            field=models.CharField(choices=[('2 gb', '2 GB'), ('3 gb', '3 GB'), ('4 gb', '4 GB'), ('6 gb', '6 GB'), ('8 gb', '8 GB'), ('12 gb', '12 GB'), ('16 gb', '16 GB'), ('18 gb', '18 GB'), ('24 gb', '24 GB')], max_length=10),
        ),
        migrations.AlterField(
            model_name='phone',
            name='storage',
            field=models.CharField(choices=[('8 gb', '8 GB'), ('16 gb', '16 GB'), ('32 gb', '32 GB'), ('64 gb', '64 GB'), ('128 gb', '128 GB'), ('256 gb', '256 GB'), ('512 gb', '512 GB'), ('1 tb', '1 TB'), ('2 tb', '2 TB')], max_length=10),
        ),
    ]
