# Generated by Django 5.2.4 on 2025-08-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('kbz', 'KBZ Pay'), ('cb', 'CB Pay'), ('wave', 'Wave Pay'), ('aya', 'Aya Pay')], default='kbz', max_length=100),
        ),
    ]
