# Generated by Django 5.2.4 on 2025-08-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_transaction_id_orderdetail_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
