# Generated by Django 5.2.4 on 2025-08-26 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_phone_ram_alter_phone_storage'),
        ('orders', '0003_delete_orderdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('phone_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.phone')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
