# Generated by Django 5.2.4 on 2025-08-26 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='transaction',
            new_name='order_id',
        ),
    ]
