# Generated by Django 5.2.4 on 2025-08-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('cancel', 'Cancel'), ('pending', 'Pending'), ('confirm', 'Confirm')], default='pending', max_length=100),
        ),
    ]
