# Generated by Django 5.2.4 on 2025-08-27 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_name',
            new_name='email',
        ),
    ]
