# Generated by Django 5.2.4 on 2025-08-27 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_user_name_order_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='user_name',
        ),
    ]
